# Generated by Django 6.0.3 on 2026-03-13 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('marathi', 'Marathi'), ('tamil', 'Tamil')], max_length=50)),
                ('event_type', models.CharField(choices=[('music', 'Music'), ('comedy', 'Comedy'), ('talk', 'Talk'), ('spiritual', 'Spiritual')], max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(choices=[('pune', 'Pune'), ('delhi', 'Delhi'), ('mumbai', 'Mumbai'), ('chennai', 'Chennai'), ('kolkata', 'Kolkata')], max_length=50)),
                ('max_capacity', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('event_date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('complete', 'Complete')], default='draft', max_length=50)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
